import type { ScenarioDefinition } from './types'

export const lubricationScenario: ScenarioDefinition = {
  id: 'lubrication-pressure-response',
  faultType: 'branchLeak',
  title: '润滑油压力异常处置',
  role: '汽机运行巡检员',
  briefing:
    '润滑油母管压力持续下降。请确认告警真实性、判断现场风险，并在事故升级前恢复系统安全状态。',
  timeLimit: 180,
  initialRisk: 32,
  riskGrowthPerSecond: 0.32,
  inventoryItems: [
    { id: 'anti-slip-ppe', label: '防滑耐油鞋套' },
    { id: 'valve-tool', label: '阀门隔离工具' },
  ],
  zones: [
    {
      id: 'oil-slip-zone',
      name: '油污滑倒危险区',
      x: 1080,
      y: 430,
      width: 210,
      height: 150,
      requiredFlags: ['anti-slip-ppe-equipped'],
      safeMessage: '已穿戴防滑耐油鞋套，进入油污外围区域时仍需谨慎通行。',
      safeRiskDelta: 2,
      missingRequirementConsequence: {
        severity: 'critical',
        message: '未穿戴防滑耐油防护用品便进入油污区域，造成人员滑倒受伤。',
        riskDelta: 55,
        scoreImpacts: { riskIdentification: -20, compliance: -20 },
      },
    },
  ],
  entities: [
    {
      id: 'remote-pressure',
      kind: 'instrument',
      name: '远传压力显示',
      x: 165,
      y: 175,
      interactionRadius: 96,
      detail: '控制系统中的远传压力信号，需要结合就地仪表判断真实性。',
      actions: [{ id: 'read-remote-pressure', label: '读取远传数值', kind: 'inspect' }],
    },
    {
      id: 'pressure-gauge',
      kind: 'instrument',
      name: '就地压力表',
      x: 520,
      y: 165,
      interactionRadius: 96,
      detail: '用于确认润滑油母管现场实际压力。',
      actions: [{ id: 'inspect-local-pressure', label: '读取就地压力', kind: 'inspect' }],
    },
    {
      id: 'main-pump',
      kind: 'pump',
      name: '主油泵',
      x: 590,
      y: 285,
      interactionRadius: 105,
      detail: '当前供油主设备，可检查运行、振动和出口状态。',
      actions: [{ id: 'inspect-main-pump', label: '检查运行状态', kind: 'inspect' }],
    },
    {
      id: 'backup-pump',
      kind: 'pump',
      name: '备用油泵',
      x: 590,
      y: 475,
      interactionRadius: 105,
      detail: '备用供油设备。操作前应先确认设备状态与启动依据。',
      actions: [
        { id: 'inspect-backup-pump', label: '检查备用状态', kind: 'inspect' },
        { id: 'start-backup-pump', label: '启动备用泵', kind: 'operate' },
      ],
    },
    {
      id: 'oil-filter',
      kind: 'filter',
      name: '润滑油过滤器',
      x: 745,
      y: 445,
      interactionRadius: 110,
      detail: '过滤器堵塞也可能造成母管压力下降。',
      actions: [
        { id: 'inspect-filter-dp', label: '读取过滤器差压', kind: 'inspect' },
        { id: 'switch-standby-filter', label: '切换备用过滤器', kind: 'operate' },
      ],
    },
    {
      id: 'control-terminal',
      kind: 'terminal',
      name: '值班控制终端',
      x: 300,
      y: 270,
      interactionRadius: 105,
      detail: '用于上报异常、记录处置过程，必要时执行受控停机保护。',
      actions: [
        { id: 'report-abnormality', label: '上报异常情况', kind: 'operate' },
        { id: 'controlled-shutdown', label: '执行受控停机', kind: 'operate' },
        { id: 'confirm-signal-fault', label: '确认信号故障', kind: 'operate' },
      ],
    },
    {
      id: 'safety-cabinet',
      kind: 'cabinet',
      name: '安全工器具柜',
      x: 150,
      y: 760,
      interactionRadius: 115,
      detail: '存放进入油污区域所需的防护用品和阀门隔离工具。',
      actions: [
        { id: 'equip-anti-slip-ppe', label: '穿戴防滑鞋套', kind: 'operate' },
        { id: 'take-valve-tool', label: '领取隔离工具', kind: 'operate' },
      ],
    },
    {
      id: 'healthy-valve',
      kind: 'valve',
      name: 'A 支路阀门',
      x: 1040,
      y: 300,
      interactionRadius: 110,
      detail: '外观无明显异常的正常供油支路。',
      actions: [
        { id: 'inspect-healthy-valve', label: '检查阀门与管路', kind: 'inspect' },
        { id: 'close-healthy-branch', label: '关闭 A 支路', kind: 'operate' },
      ],
    },
    {
      id: 'branch-valve',
      kind: 'valve',
      name: 'B 支路阀门',
      x: 1040,
      y: 475,
      interactionRadius: 110,
      detail: '邻近区域存在油迹，需要判断是否为泄漏来源。',
      actions: [
        { id: 'inspect-leaking-valve', label: '检查阀门与管路', kind: 'inspect' },
        { id: 'close-leaking-branch', label: '关闭 B 支路', kind: 'operate' },
      ],
    },
    {
      id: 'oil-leak',
      kind: 'hazard',
      name: '高温漏油区域',
      x: 1150,
      y: 530,
      interactionRadius: 120,
      detail: '地面存在高温润滑油，可在安全边界外观察，直接进入会造成人身伤害。',
      actions: [
        { id: 'observe-oil-leak', label: '在边界外观察', kind: 'inspect' },
        { id: 'enter-oil-leak', label: '直接进入区域', kind: 'enter' },
      ],
    },
  ],
  clues: [
    { id: 'remote-pressure-low', title: '远传低压', detail: '远传压力显示 0.11 MPa，但单一信号不足以确认真实低压。' },
    { id: 'local-pressure-low', title: '现场压力异常', detail: '就地压力为 0.12 MPa，与远传告警一致，可排除单纯信号故障。' },
    { id: 'main-pump-running', title: '主油泵仍在运行', detail: '主泵运行声音和振动基本正常，出口压力偏低。' },
    { id: 'backup-pump-ready', title: '备用泵可用', detail: '备用泵电源、油位和远方控制状态正常，具备启动条件。' },
    { id: 'filter-dp-normal', title: '过滤器差压正常', detail: '过滤器前后差压在正常范围，可暂时排除严重堵塞。' },
    { id: 'healthy-branch-dry', title: 'A 支路外观正常', detail: 'A 支路阀门及法兰处干燥，无明显泄漏痕迹。' },
    { id: 'leak-source-found', title: '发现泄漏来源', detail: 'B 支路阀门下游法兰持续渗油，与地面油迹方向一致。' },
    { id: 'pressure-recovering', title: '备用供油有效', detail: '备用泵启动后母管压力开始回升，备用供油通道正常。' },
    { id: 'leak-isolated', title: '异常支路已隔离', detail: '关闭 B 支路后压力稳定，漏油范围停止扩大。' },
  ],
  objectives: [
    { id: 'verify-alarm', title: '确认告警性质', description: '结合远传与现场信息判断告警是否真实。', completionFlags: ['pressure-confirmed'], trainingHint: '先比较远传压力与就地压力，不要仅凭单一信号执行设备操作。' },
    { id: 'identify-cause', title: '定位异常来源', description: '检查相关设备并识别造成低压的主要原因。', completionFlags: ['leak-identified'], trainingHint: '检查主泵、过滤器和两条支路，利用排除法定位异常来源。' },
    { id: 'control-risk', title: '控制风险扩散', description: '选择合适方式保护设备，避免异常进一步扩大。', completionFlags: ['supply-protected'], trainingHint: '隔离泄漏前，需要先建立备用供油或执行受控停机保护。' },
    { id: 'restore-safety', title: '恢复安全状态', description: '隔离异常来源并使系统状态稳定。', completionFlags: ['leak-isolated'], trainingHint: '领取隔离工具后，确认要关闭的是发生泄漏的支路。' },
    { id: 'complete-report', title: '完成规范上报', description: '记录异常和处置结果，形成闭环。', completionFlags: ['response-reported'], trainingHint: '通过值班控制终端上报异常和处置结果。' },
  ],
  assessmentDimensions: [
    { id: 'riskIdentification', label: '风险识别', maxScore: 20 },
    { id: 'diagnosis', label: '故障诊断', maxScore: 25 },
    { id: 'compliance', label: '操作规范', maxScore: 20 },
    { id: 'effectiveness', label: '处置效果', maxScore: 25 },
    { id: 'efficiency', label: '响应效率', maxScore: 10 },
  ],
  rules: [
    { actionId: 'read-remote-pressure', successMessage: '远传压力显示 0.11 MPa，需要就地复核。', addFlags: ['remote-pressure-read'], addClueIds: ['remote-pressure-low'], riskDelta: 1, scoreImpacts: { riskIdentification: 1, diagnosis: 1 } },
    { actionId: 'inspect-local-pressure', successMessage: '就地压力仅 0.12 MPa，确认低压告警真实。', addFlags: ['pressure-confirmed'], addClueIds: ['local-pressure-low'], riskDelta: 2, scoreImpacts: { riskIdentification: 6, diagnosis: 4 } },
    { actionId: 'inspect-main-pump', successMessage: '主油泵仍在运行，出口压力偏低。', addFlags: ['main-pump-checked'], addClueIds: ['main-pump-running'], riskDelta: 1, scoreImpacts: { diagnosis: 4 } },
    { actionId: 'inspect-backup-pump', successMessage: '备用泵具备启动条件。', addFlags: ['backup-checked'], addClueIds: ['backup-pump-ready'], riskDelta: 1, scoreImpacts: { compliance: 3 } },
    {
      actionId: 'start-backup-pump',
      requiredFlags: ['pressure-confirmed', 'backup-checked'],
      successMessage: '备用泵启动，母管压力开始恢复。',
      addFlags: ['backup-running', 'supply-protected'],
      addClueIds: ['pressure-recovering'],
      riskDelta: -16,
      scoreImpacts: { compliance: 4, effectiveness: 15 },
      invalidConsequence: { severity: 'minor', message: '启动依据或设备状态尚未确认，本次启动指令被拦截。', riskDelta: 8, scoreImpacts: { compliance: -6 } },
    },
    { actionId: 'inspect-filter-dp', successMessage: '过滤器差压正常，可排除严重堵塞。', addFlags: ['filter-checked'], addClueIds: ['filter-dp-normal'], riskDelta: 1, scoreImpacts: { diagnosis: 4 } },
    {
      actionId: 'switch-standby-filter',
      successMessage: '',
      riskDelta: 0,
      scoreImpacts: {},
      invalidConsequence: { severity: 'minor', message: '过滤器差压正常，无依据切换备用过滤器。', riskDelta: 5, scoreImpacts: { compliance: -4 } },
    },
    {
      actionId: 'equip-anti-slip-ppe',
      successMessage: '已穿戴防滑耐油鞋套，可进入油污外围区域。',
      addFlags: ['anti-slip-ppe-equipped'],
      addItemIds: ['anti-slip-ppe'],
      riskDelta: 0,
      scoreImpacts: { compliance: 2 },
    },
    {
      actionId: 'take-valve-tool',
      successMessage: '已领取阀门隔离工具。',
      addFlags: ['valve-tool-carried'],
      addItemIds: ['valve-tool'],
      riskDelta: 0,
      scoreImpacts: { compliance: 2 },
    },
    {
      actionId: 'report-abnormality',
      requiredFlags: ['pressure-confirmed', 'leak-identified'],
      successMessage: '异常现象、诊断依据和当前风险已上报值班负责人。',
      addFlags: ['response-reported'],
      riskDelta: 0,
      scoreImpacts: { compliance: 13 },
      invalidConsequence: { severity: 'minor', message: '现场信息不足，异常上报缺少必要的诊断依据。', riskDelta: 2, scoreImpacts: { compliance: -3 } },
    },
    {
      actionId: 'controlled-shutdown',
      requiredFlags: ['pressure-confirmed', 'leak-identified'],
      successMessage: '已执行受控停机，关键设备进入保护状态，可继续隔离泄漏支路。',
      addFlags: ['system-protected', 'supply-protected', 'response-reported'],
      riskDelta: -24,
      scoreImpacts: { compliance: 6, effectiveness: 10 },
      invalidConsequence: { severity: 'minor', message: '故障性质尚未确认，受控停机申请被值班负责人驳回。', riskDelta: 4, scoreImpacts: { compliance: -4 } },
    },
    {
      actionId: 'confirm-signal-fault',
      successMessage: '',
      riskDelta: 0,
      scoreImpacts: {},
      invalidConsequence: { severity: 'minor', message: '就地压力同样偏低，不能判定为远传信号故障。', riskDelta: 4, scoreImpacts: { diagnosis: -5 } },
    },
    { actionId: 'inspect-healthy-valve', successMessage: 'A 支路外观正常，未发现泄漏。', addFlags: ['healthy-branch-checked'], addClueIds: ['healthy-branch-dry'], riskDelta: 1, scoreImpacts: { diagnosis: 4 } },
    {
      actionId: 'close-healthy-branch',
      successMessage: '',
      riskDelta: 0,
      scoreImpacts: {},
      invalidConsequence: { severity: 'critical', message: '误关正常供油 A 支路，造成润滑油供应中断。', riskDelta: 55, scoreImpacts: { compliance: -20, effectiveness: -25 } },
    },
    { actionId: 'inspect-leaking-valve', successMessage: 'B 支路下游法兰持续渗油，确认泄漏来源。', addFlags: ['leak-identified'], addClueIds: ['leak-source-found'], riskDelta: 2, scoreImpacts: { riskIdentification: 10, diagnosis: 9 } },
    {
      actionId: 'close-leaking-branch',
      requiredFlags: ['pressure-confirmed', 'supply-protected', 'leak-identified', 'valve-tool-carried'],
      successMessage: 'B 支路已隔离，润滑油压力恢复稳定。',
      addFlags: ['leak-isolated'],
      addClueIds: ['leak-isolated'],
      riskDelta: -28,
      scoreImpacts: { compliance: 4, effectiveness: 10 },
      invalidConsequence: { severity: 'critical', message: '诊断、系统保护或隔离工具条件不足，强行操作导致系统失稳。', riskDelta: 45, scoreImpacts: { compliance: -20, effectiveness: -25 } },
    },
    { actionId: 'observe-oil-leak', successMessage: '在安全边界外确认油迹来自 B 支路方向。', addFlags: ['leak-identified'], addClueIds: ['leak-source-found'], riskDelta: 1, scoreImpacts: { riskIdentification: 10, diagnosis: 7 } },
    {
      actionId: 'enter-oil-leak',
      successMessage: '',
      riskDelta: 0,
      scoreImpacts: {},
      invalidConsequence: { severity: 'critical', message: '直接进入高温漏油区域，触发滑倒与高温接触人身伤害事故。', riskDelta: 60, scoreImpacts: { riskIdentification: -20, compliance: -20 } },
    },
  ],
  completionFlags: ['pressure-confirmed', 'leak-identified', 'supply-protected', 'leak-isolated', 'response-reported'],
}
